on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: moexpense.atwebpages.com
        username: 4011122_moexpense
        password: ${{ secrets.ftp_pass }}
        protocol: ftps
        server-dir: moexpense.atwebpages.com/